# Numpy Introduction
(Numerical Python)
# What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

# Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.


# Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [28]:
import numpy as np

# if onew string character is used in an array it will assue whole array to be like a string array
arr = np.array([1,2,3,4,5,6,7,'rather'])
print(arr)
print(type(arr))
print(type(arr[0]))
print(arr[0]+arr[1])


['1' '2' '3' '4' '5' '6' '7' 'rather']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
12


In [29]:
# but if all are the numbers then it will consoider them as the numbers
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))
print(type(arr[0]))
print("Sum = ",arr[0]+arr[1])

arr = np.array([1.1,2,3,4,5,6,7])
print(arr)
print(type(arr[0]))
print("Sum =",arr[0]+arr[1],"aa ok")

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.int32'>
Sum =  3
[1.1 2.  3.  4.  5.  6.  7. ]
<class 'numpy.float64'>
Sum = 3.1 aa ok


In [25]:
# to check the python and the numpy version 
import platform
print("Python Version",platform.python_version())
print("NumPy Version",np.__version__)

Python Version 3.11.5
NumPy Version 1.24.3


# Dimensions in arrays

# 0-D Arrays (scalars)

In [31]:
arr = np.array(9110)
print(arr)

9110


# 1-D Arrays
uni-dimensional arrays containing the lements of 0-d arrays

In [32]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print("Array : ",arr)

Array :  [0 1 2 3 4 5 6 7 8 9]


# 2-D Arrays
two dimensional arrays containing 1-d arrays as their elements 

In [35]:
arr = np.array([[1,2], [3,4]])
print("2d Array \n",arr)

2d Array 
 [[1 2]
 [3 4]]


# 3-D Arrays 
three dimensional arrays containing 2-d arrays as their elements

In [36]:
arr = np.array([[[1,2],[3,4]], [[2,1],[ 4,3]]])
print("3d Array \n",arr)

3d Array 
 [[[1 2]
  [3 4]]

 [[2 1]
  [4 3]]]


# Checking the number of dimensions of an array
there is an attribute in python named "ndim" that returns an integer telling the number of dimensions that an array have

In [37]:
print("Dimensions of above array : ",arr.ndim)

Dimensions of above array :  3


# Specify Higher Dimensional Arrays
an array can be defined to have a specific number of dimensions using  "ndmin" argument

In [63]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr[0][0][0][0][0])
print(arr[0][0][0][0])
print(arr[0][0][0])
print(arr[0][0])
print(arr[0])
print(arr)
print("Number of dimensions : ", arr.ndim)

1
[1 2 3 4]
[[1 2 3 4]]
[[[1 2 3 4]]]
[[[[1 2 3 4]]]]
[[[[[1 2 3 4]]]]]
Number of dimensions :  5


# Array Indexing

1-D Array Indexing

In [65]:
arr = np.array([1,2,3,4,5])
print(arr[1])

2


2-D Array Indexing

In [68]:
arr = np.array([[1,2,7],[3,4,5]])
print(arr[0,1])

2


3-D Array Indexing

In [79]:
arr = np.array([[[1,2,6],[3,4,7]],[[2,1,9],[4,3,11]]])
print("Index [1] : \n",arr[1])
print("Index [1,1] : \n",arr[1,1])
print("Index [1,1,1] : \n",arr[1,1,1])

Index [1] : 
 [[ 2  1  9]
 [ 4  3 11]]
Index [1,1] : 
 [ 4  3 11]
Index [1,1,1] : 
 3


Negative Indexing

In [93]:
print("Index [-1] : \n",arr[-1])
print("Index [1,-1] : ",arr[1,-1])
print("Index [1,1,-1] : ",arr[1,1,-0])
print("Index [1,1,-1] : ",arr[1,1,-1])
print("Index [1,1,-1] : ",arr[1,1,-2])

Index [-1] : 
 [[ 2  1  9]
 [ 4  3 11]]
Index [1,-1] :  [ 4  3 11]
Index [1,1,-1] :  4
Index [1,1,-1] :  11
Index [1,1,-1] :  3
